export enum todoActionTypes {
  FETCH_TODO = "FETCH_TODO",
  FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS",
  UPDATE_TODO = "UPDATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  TODO_ERROR = "TODO_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR"
}
